version: "3.5"

services:
  db:
    image: 'postgres:13'
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ssh_manager_db
      - POSTGRES_USER=jabka
      - POSTGRES_PASSWORD=test123
      - POSTGRES_PORT=5432
    ports:  # for pgadmin
      - "5432:5432"
    expose:
      - 5432
  ssh_manager:
    build: ssh_manager/
    ports:
      - "8000:8000"
    restart: always
    environment:
      - POSTGRES_DB=ssh_manager_db
      - POSTGRES_USER=jabka
      - POSTGRES_PASSWORD=test123
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
networks:
  default:
    name: postgre-service_default